/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package trabajo_grupal;

import controller.Cargar_Archivar;
import controller.Modelo_de_Tabla;
import controller.Utilidades;
import java.util.Arrays;

/**
 *
 * @author Carlos Zumba
 */
public class Materias_Ciclo extends javax.swing.JDialog {

    public static String[] Carreras = null;
    Utilidades u = new Utilidades();
    Cargar_Archivar ch = new Cargar_Archivar();
    Modelo_de_Tabla m = new Modelo_de_Tabla();
    String[][] materias = null;
    String carrera = "";

    public Materias_Ciclo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarCarrera();
        cargarTabla("data.Computacion");
        cbxciclos.enable(false);
    }

    private void cargarCarrera() {
        CxbCarrera.removeAllItems();
        for (String carrera : ch.retornInformation("data.carreras")) {
            CxbCarrera.addItem(carrera);
        }
    }

    public void cargarTabla(String archivo) {
        try {
            materias = u.listAll(archivo);
            System.out.println(materias.length);
            m.setData(materias);
            tbtMaterias.setModel(m);
            tbtMaterias.updateUI();

        } catch (Exception e) {
            System.out.println("asdas");
        }

    }

    public void caragrmateira() {
        tbtMaterias.removeAll();
        String Sleccio = (String) cbxciclos.getSelectedItem();
        m.setData(ch.FiltrarMaterias(materias, Sleccio));
        tbtMaterias.setModel(m);
        tbtMaterias.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CxbCarrera = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbtMaterias = new javax.swing.JTable();
        cbxciclos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Carreras y Ciclo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 0, 200, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Carreras:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 100, 80, 30);

        CxbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CxbCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxbCarreraActionPerformed(evt);
            }
        });
        jPanel1.add(CxbCarrera);
        CxbCarrera.setBounds(110, 100, 100, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Ciclo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 100, 90, 30);

        jPanel4.setBackground(new java.awt.Color(51, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Materias"));

        tbtMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbtMaterias);

        jPanel4.add(jScrollPane2);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 160, 460, 450);

        cbxciclos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxciclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxciclosActionPerformed(evt);
            }
        });
        jPanel1.add(cbxciclos);
        cbxciclos.setBounds(300, 100, 100, 30);

        jLabel5.setText("Mientras no se seleccione una carrera no se mostraran materias");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 140, 360, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Agregrar Materia");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(590, 100, 160, 30);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(630, 160, 80, 30);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(630, 200, 190, 40);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(630, 260, 70, 40);

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(630, 320, 71, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Numero de ciclo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(500, 160, 120, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Materia");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(560, 210, 90, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Horas");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(570, 270, 50, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Siglas");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(570, 320, 60, 20);

        jButton1.setText("Crear materia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(620, 423, 120, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 10, 860, 650);

        setSize(new java.awt.Dimension(877, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void rellenarComboCiclos(String archivo) {
        for (String ciclos : ch.retornciclos(archivo)) {
            cbxciclos.addItem(ciclos);
            // }
        }
        cbxciclos.updateUI();
        cbxciclos.enable();
    }

    private void CxbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxbCarreraActionPerformed
        carrera = (String) CxbCarrera.getSelectedItem();
        System.out.println(CxbCarrera.getSelectedItem());
        cbxciclos.removeAllItems();
        if (null == carrera) {
            cbxciclos.enable(false);
        } else {
            switch (carrera) {
                case "Computacion" -> {
                    rellenarComboCiclos("data.Computacion");
                    cargarTabla("data.Computacion");
                }
                case "Electricidad" -> {
                    rellenarComboCiclos("data.Electricidad");
                    cargarTabla("data.Electricidad");
                }
                case "Minas" -> {
                    rellenarComboCiclos("data.Minas");
                    cargarTabla("data.Minas");
                }
                case "Electromecanica" -> {
                    rellenarComboCiclos("data.Electromecanica");
                    cargarTabla("data.Electromecanica");
                }
                case "Ingenieria Automotriz" -> {
                    rellenarComboCiclos("data.IngenieriaAutomotriz");
                    cargarTabla("data.IngenieriaAutomotriz");
                }
                default -> {
                    cbxciclos.enable(false);
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CxbCarreraActionPerformed
    public void rellenarTablaMaterias(String archivo, String Sleccio) {
        try {
            materias = u.listAll(archivo);
            m.setData(ch.FiltrarMaterias(materias, Sleccio));
            tbtMaterias.setModel(m);
            tbtMaterias.updateUI();
        } catch (Exception e) {
            System.out.println("asdas");
        }
    }
    private void cbxciclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxciclosActionPerformed
        if (cbxciclos.getSelectedIndex() == -1) {
            return;
        }
        String opcion = (String) cbxciclos.getSelectedItem();
        try {
            switch (carrera) {
                case "Computacion" ->
                    rellenarTablaMaterias("data.Computacion", opcion);
                case "Electricidad" ->
                    rellenarTablaMaterias("data.Electricidad", opcion);
                case "Minas" ->
                    rellenarTablaMaterias("data.Minas", opcion);
                case "Electromecanica" ->
                    rellenarTablaMaterias("data.Electromecanica", opcion);
                case "Ingenieria Automotriz" ->
                    rellenarTablaMaterias("data.IngenieriaAutomotriz", opcion);
                default ->
                    tbtMaterias.removeAll();
            }
        } catch (Exception e) {
            System.out.println("asdas");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_cbxciclosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String materianueva = (jTextField1.getText()+ "\t"+ "ciclo"+"\t" + jTextField3.getText() + "\t" + jTextField4.getText() + "\t" + jTextField5.getText() + "\n");
        try {
            switch (carrera) {
                case "Computacion":
                    u.save(materianueva, "data.Computacion");
                    cargarTabla("data.Computacion");
                    break;
                case "Electricidad":
                    u.save(materianueva, "data.Electricidad");
                    cargarTabla("data.Electricidad");
                    break;
                case "Minas":
                    u.save(materianueva, "data.Minas");
                    cargarTabla("data.Minas");
                    break;
                case "Electromecanica":
                    u.save(materianueva, "data.Electromecanica");
                    cargarTabla("data.Electromecanica");
                    break;
                case "Ingenieria Automotriz":
                    u.save(materianueva, "data.IngenieriaAutomotriz");
                    cargarTabla("data.Automotriz");
                    break;
                default:
                    tbtMaterias.removeAll();
                    break;
            }
        } catch (Exception e) {
            System.out.println("asdas");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materias_Ciclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materias_Ciclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materias_Ciclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materias_Ciclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Materias_Ciclo dialog = new Materias_Ciclo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CxbCarrera;
    private javax.swing.JComboBox<String> cbxciclos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tbtMaterias;
    // End of variables declaration//GEN-END:variables
}
