/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package trabajo_grupal;

import controller.Cargar_Archivar;
import controller.Modelo_de_Tabla;
import controller.Utilidades;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Carlos Zumba
 */
public class Materias_Ciclo extends javax.swing.JDialog {

    public static String[] Carreras = null;
    Utilidades u = new Utilidades();
    Cargar_Archivar ch = new Cargar_Archivar();
    Modelo_de_Tabla m = new Modelo_de_Tabla();
    public static String[][] materias;

    /**
     * Creates new form Materias_Ciclo
     *
     * @throws java.io.IOException
     */
    public Materias_Ciclo(java.awt.Frame parent, boolean modal) throws IOException {
        super(parent, modal);
        initComponents();
        cargarCarrera();
        cargarTabla();
    }

    private void cargarCarrera() {
        CxbCarrera.removeAllItems();
        for (String carrera : ch.retornInformation("data.carreras")) {
            CxbCarrera.addItem(carrera);
        }
    }

    public void cargarTabla() throws IOException {
        materias = u.listAll("data.Computacion");
        m.setData(materias);
        tbtMaterias.setModel(m);
        tbtMaterias.updateUI();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CxbCarrera = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbtMaterias = new javax.swing.JTable();
        cbxciclos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Carreras y Ciclo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 40, 200, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Carreras:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 100, 80, 30);

        CxbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CxbCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxbCarreraActionPerformed(evt);
            }
        });
        jPanel1.add(CxbCarrera);
        CxbCarrera.setBounds(110, 100, 100, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Ciclo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 100, 90, 30);

        jPanel4.setBackground(new java.awt.Color(51, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Materias"));

        tbtMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbtMaterias);

        jPanel4.add(jScrollPane2);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(130, 160, 470, 470);

        cbxciclos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxciclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxciclosActionPerformed(evt);
            }
        });
        jPanel1.add(cbxciclos);
        cbxciclos.setBounds(300, 100, 100, 30);

        jLabel5.setText("Mientras no se seleccione una carrera no se mostraran materias");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 140, 360, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 630);

        setSize(new java.awt.Dimension(748, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void CxbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxbCarreraActionPerformed
        String Sleccio = (String) CxbCarrera.getSelectedItem();
        CxbCarrera.getSelectedItem();
        System.out.println(CxbCarrera.getSelectedItem());
        cbxciclos.removeAllItems();
        if ("Computacion".equals(Sleccio)) {
            cbxciclos.removeAllItems();
            for (String ciclos : ch.retornciclos("data.Computacion")) {
                cbxciclos.addItem(ciclos);
                // }
            }
            cbxciclos.updateUI();
        }
        //if (CxbCarrera.getSelectedItem() == "Computacion") {
        if ("Electricidad".equals(Sleccio)) {
            for (String ciclos : ch.retornciclos("data.Electricidad")) {
                cbxciclos.addItem(ciclos);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CxbCarreraActionPerformed

    private void cbxciclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxciclosActionPerformed
        tbtMaterias.removeAll();
//        String[][] temporal = new String[7][];
//        int contador = 0;
//        for (String[] fila : this.materias) {
//            if (fila[0] == cbxciclos.getSelectedItem()) {
//                temporal[contador++] = fila;
//            }
//        }
        //m.setData(temporal);
        tbtMaterias.updateUI();
// TODO add your handling code here:
    }//GEN-LAST:event_cbxciclosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materias_Ciclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materias_Ciclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materias_Ciclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materias_Ciclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Materias_Ciclo dialog = new Materias_Ciclo(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Materias_Ciclo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CxbCarrera;
    private javax.swing.JComboBox<String> cbxciclos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbtMaterias;
    // End of variables declaration//GEN-END:variables
}
